services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: supersecret
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: [redis-server, --appendonly, yes]
    volumes:
      - redis:/data

  app:
    image: nextcloud:stable
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - 8080:80
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: supersecret
      REDIS_HOST: redis
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: anothersecret
      NEXTCLOUD_TRUSTED_DOMAINS: localhost 127.0.0.1
    volumes:
      - nextcloud:/var/www/html
      - /mnt/nextcloud-data:/var/www/html/data
      - config:/var/www/html/config
      - custom_apps:/var/www/html/custom_apps

  cron:
    image: nextcloud:stable
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - nextcloud:/var/www/html
      - /mnt/nextcloud-data/:/var/www/html/data
      - config:/var/www/html/config
      - custom_apps:/var/www/html/custom_apps
    entrypoint: /cron.sh

volumes:
  db:
  redis:
  nextcloud:
  config:
  custom_apps:
  # (No top-level 'data:' anymore since we bind-mount the RAID)
